### ISSUE TITLE
README parallel scalability

### ISSUE THREAD

**Issue by krober10nd** [krober10nd/spyro#52]
@Olender could you put the image from the paper on the README and add a short blurb about it? I think it tells a more complete performance story than the current figure...

**Comment by Olender** [comment]
![readmescalingfigure](https://user-images.githubusercontent.com/45005909/127851197-eb323449-deb9-4338-bc97-7a1ec81ff766.png)
Alright, uploading here to reference it on the readme.

**Comment by Olender** [comment]
I recently created a PR with an update and the relevant files
