### ISSUE TITLE
usage of `io.isowner`

### ISSUE THREAD

**Issue by krober10nd** [krober10nd/spyro#8]
is awkward and has to be used twice otherwise `solvers` error because no solutions are returned for that core. 

My suggestion is to:

remove `isowner` from `solvers` altogether and make the user leave it in their "shot`` loop. 

IMO, this behavior sending shots to cores should not be automatic. There are several FWI situations where FWI loop require more control over which shots are computed. 

solvers should just compute the solution.

**Comment by Olender** [comment]
> There are several FWI situations where FWI loop require more control over which shots are computed.

Which situations would those be? And wouldn't those situations be better covered by adding a custom rule? I feel like we've had this discussion before. 

What exactly do you propose? That the loop of sending shots to processors be defined on the main API, or to have a separate method that does this and calls the solvers within?

**Comment by krober10nd** [comment]
stochastic-LBFGS, multiscale FWI with progressively shorter offset, etc. No custom rules. 

I proposed exactly what I said in the original post: remove isowner from solvers altogether and make the user leave it in their "shot`` loop.

solvers should compute the solution to an equation nothing more.
